knowLib/Controllers/ArtigoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using knowLib.Data;
using knowLib.Models;

namespace knowLib.Controllers
{
    public class ArtigoesController : Controller
    {
        private AddDbContext db = new AddDbContext();

        // GET: Artigoes
        public async Task<ActionResult> Index()
        {
            return View(await db.Artigos.ToListAsync());
        }

        // GET: Artigoes/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artigo artigo = await db.Artigos.FindAsync(id);
            if (artigo == null)
            {
                return HttpNotFound();
            }
            return View(artigo);
        }

        // GET: Artigoes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Artigoes/Create
        // Para proteger-se contra ataques de excesso de postagem, ative as propriedades específicas às quais deseja se associar. 
        // Para obter mais detalhes, confira https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Titulo,Resumo,DOI,Arquivo,DataPublicacao,Revista,Volume,Edicao")] Artigo artigo)
        {
            if (ModelState.IsValid)
            {
                db.Artigos.Add(artigo);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(artigo);
        }

        // GET: Artigoes/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artigo artigo = await db.Artigos.FindAsync(id);
            if (artigo == null)
            {
                return HttpNotFound();
            }
            return View(artigo);
        }

        // POST: Artigoes/Edit/5
        // Para proteger-se contra ataques de excesso de postagem, ative as propriedades específicas às quais deseja se associar. 
        // Para obter mais detalhes, confira https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Titulo,Resumo,DOI,Arquivo,DataPublicacao,Revista,Volume,Edicao")] Artigo artigo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(artigo).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(artigo);
        }

        // GET: Artigoes/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artigo artigo = await db.Artigos.FindAsync(id);
            if (artigo == null)
            {
                return HttpNotFound();
            }
            return View(artigo);
        }

        // POST: Artigoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Artigo artigo = await db.Artigos.FindAsync(id);
            db.Artigos.Remove(artigo);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

knowLib/Controllers/AutorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using knowLib.Data;
using knowLib.Models;

namespace knowLib.Controllers
{
    public class AutorsController : Controller
    {
        private AddDbContext db = new AddDbContext();

        // GET: Autors
        public async Task<ActionResult> Index()
        {
            return View(await db.Autores.ToListAsync());
        }

        // GET: Autors/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Autor autor = await db.Autores.FindAsync(id);
            if (autor == null)
            {
                return HttpNotFound();
            }
            return View(autor);
        }

        // GET: Autors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Autors/Create
        // Para proteger-se contra ataques de excesso de postagem, ative as propriedades específicas às quais deseja se associar. 
        // Para obter mais detalhes, confira https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Nome,Instituicao,EmailContato,Bio,OrcId")] Autor autor)
        {
            if (ModelState.IsValid)
            {
                db.Autores.Add(autor);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(autor);
        }

        // GET: Autors/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Autor autor = await db.Autores.FindAsync(id);
            if (autor == null)
            {
                return HttpNotFound();
            }
            return View(autor);
        }

        // POST: Autors/Edit/5
        // Para proteger-se contra ataques de excesso de postagem, ative as propriedades específicas às quais deseja se associar. 
        // Para obter mais detalhes, confira https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Nome,Instituicao,EmailContato,Bio,OrcId")] Autor autor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(autor).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(autor);
        }

        // GET: Autors/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Autor autor = await db.Autores.FindAsync(id);
            if (autor == null)
            {
                return HttpNotFound();
            }
            return View(autor);
        }

        // POST: Autors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Autor autor = await db.Autores.FindAsync(id);
            db.Autores.Remove(autor);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

knowLib/Controllers/AvaliacaosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using knowLib.Data;
using knowLib.Models;

namespace knowLib.Controllers
{
    public class AvaliacaosController : Controller
    {
        private AddDbContext db = new AddDbContext();

        // GET: Avaliacaos
        public async Task<ActionResult> Index()
        {
            var avaliacoes = db.Avaliacoes.Include(a => a.Artigo).Include(a => a.Ebook).Include(a => a.Usuario);
            return View(await avaliacoes.ToListAsync());
        }

        // GET: Avaliacaos/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Avaliacao avaliacao = await db.Avaliacoes.FindAsync(id);
            if (avaliacao == null)
            {
                return HttpNotFound();
            }
            return View(avaliacao);
        }

        // GET: Avaliacaos/Create
        public ActionResult Create()
        {
            ViewBag.ArtigoId = new SelectList(db.Artigos, "Id", "Titulo");
            ViewBag.EbookId = new SelectList(db.Ebooks, "Id", "Titulo");
            ViewBag.UsuarioId = new SelectList(db.Usuario, "Id", "Email");
            return View();
        }

        // POST: Avaliacaos/Create
        // Para proteger-se contra ataques de excesso de postagem, ative as propriedades específicas às quais deseja se associar. 
        // Para obter mais detalhes, confira https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Comentario,Nota,DataAvaliacao,UsuarioId,EbookId,ArtigoId")] Avaliacao avaliacao)
        {
            if (ModelState.IsValid)
            {
                db.Avaliacoes.Add(avaliacao);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.ArtigoId = new SelectList(db.Artigos, "Id", "Titulo", avaliacao.ArtigoId);
            ViewBag.EbookId = new SelectList(db.Ebooks, "Id", "Titulo", avaliacao.EbookId);
            ViewBag.UsuarioId = new SelectList(db.Usuario, "Id", "Email", avaliacao.UsuarioId);
            return View(avaliacao);
        }

        // GET: Avaliacaos/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Avaliacao avaliacao = await db.Avaliacoes.FindAsync(id);
            if (avaliacao == null)
            {
                return HttpNotFound();
            }
            ViewBag.ArtigoId = new SelectList(db.Artigos, "Id", "Titulo", avaliacao.ArtigoId);
            ViewBag.EbookId = new SelectList(db.Ebooks, "Id", "Titulo", avaliacao.EbookId);
            ViewBag.UsuarioId = new SelectList(db.Usuario, "Id", "Email", avaliacao.UsuarioId);
            return View(avaliacao);
        }

        // POST: Avaliacaos/Edit/5
        // Para proteger-se contra ataques de excesso de postagem, ative as propriedades específicas às quais deseja se associar. 
        // Para obter mais detalhes, confira https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Comentario,Nota,DataAvaliacao,UsuarioId,EbookId,ArtigoId")] Avaliacao avaliacao)
        {
            if (ModelState.IsValid)
            {
                db.Entry(avaliacao).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.ArtigoId = new SelectList(db.Artigos, "Id", "Titulo", avaliacao.ArtigoId);
            ViewBag.EbookId = new SelectList(db.Ebooks, "Id", "Titulo", avaliacao.EbookId);
            ViewBag.UsuarioId = new SelectList(db.Usuario, "Id", "Email", avaliacao.UsuarioId);
            return View(avaliacao);
        }

        // GET: Avaliacaos/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Avaliacao avaliacao = await db.Avaliacoes.FindAsync(id);
            if (avaliacao == null)
            {
                return HttpNotFound();
            }
            return View(avaliacao);
        }

        // POST: Avaliacaos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Avaliacao avaliacao = await db.Avaliacoes.FindAsync(id);
            db.Avaliacoes.Remove(avaliacao);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

knowLib/Controllers/EbooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using knowLib.Data;
using knowLib.Models;

namespace knowLib.Controllers
{
    public class EbooksController : Controller
    {
        private AddDbContext db = new AddDbContext();

        // GET: Ebooks
        public async Task<ActionResult> Index()
        {
            return View(await db.Ebooks.ToListAsync());
        }

        // GET: Ebooks/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ebook ebook = await db.Ebooks.FindAsync(id);
            if (ebook == null)
            {
                return HttpNotFound();
            }
            return View(ebook);
        }

        // GET: Ebooks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Ebooks/Create
        // Para proteger-se contra ataques de excesso de postagem, ative as propriedades específicas às quais deseja se associar. 
        // Para obter mais detalhes, confira https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Titulo,Resumo,ISBN,Arquivo,DataPublicacao,NumeroPaginas,Idioma")] Ebook ebook)
        {
            if (ModelState.IsValid)
            {
                db.Ebooks.Add(ebook);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(ebook);
        }

        // GET: Ebooks/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ebook ebook = await db.Ebooks.FindAsync(id);
            if (ebook == null)
            {
                return HttpNotFound();
            }
            return View(ebook);
        }

        // POST: Ebooks/Edit/5
        // Para proteger-se contra ataques de excesso de postagem, ative as propriedades específicas às quais deseja se associar. 
        // Para obter mais detalhes, confira https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Titulo,Resumo,ISBN,Arquivo,DataPublicacao,NumeroPaginas,Idioma")] Ebook ebook)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ebook).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(ebook);
        }

        // GET: Ebooks/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ebook ebook = await db.Ebooks.FindAsync(id);
            if (ebook == null)
            {
                return HttpNotFound();
            }
            return View(ebook);
        }

        // POST: Ebooks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Ebook ebook = await db.Ebooks.FindAsync(id);
            db.Ebooks.Remove(ebook);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

knowLib/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Know Lib</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/Content/bootstrap.min.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" style="padding: 0px;">
        <div class="container">
            <a class="navbar-brand fs-2 mt-2 mb-2" href="/Home/Index">Know Lib</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            @Html.ActionLink("Home", "Index", "ArtigosEbooks", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("About", "About", "Home", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Sair", "Logout", "Account", null, new { @class = "nav-link" })
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            @Html.ActionLink("Login", "Login", "Account", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Register", "Register", "Account", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("About", "About", "Home", null, new { @class = "nav-link" })
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content" style="margin-top: 70px;">
        @RenderBody()
        <hr />
        <footer class="text-center">
            <p>&copy; @DateTime.Now.Year - Know Lib</p>
        </footer>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

knowLib/Views/Shared/_LayoutGerente.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title Know Lib</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" style="padding: 0px;">
        <div class="container">
            <p class="navbar-brand fs-2 mt-2 mb-2">  @Html.ActionLink("Know Lib", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</p>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        @Html.ActionLink("Teste", "Index", "Membro", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Artigos", "Index", "Artigoes", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Autores", "Index", "Autors", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Avaliação", "Index", "Avaliacaos", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Ebook", "Index", "Ebooks", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Categorias", "Index", "Categorias", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    @*<li class="nav-item">
            @Html.ActionLink("Projetos", "Index", "Projetos", new { area = "" }, new { @class = "nav-link" })
        </li>
        <li class="nav-item">
            @Html.ActionLink("Equipes", "Index", "Equipes", new { area = "" }, new { @class = "nav-link" })
        </li>*@
                    <li class="nav-item">
                        @Html.ActionLink("Sair", "Logout", "Account", new { area = "" }, new { @class = "nav-link" })
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content" style="margin-top: 70px;">
        @RenderBody()
        <hr />
        <footer class="text-center">
            <p>&copy; @DateTime.Now.Year - Know Lib</p>
        </footer>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>